### ISSUE TITLE
Healthcheck

### ISSUE THREAD

**Issue by KucharczykL** [linuxserver/docker-radarr#104]
Would there be interest in adding healthcheck to this image? Something like: https://github.com/KucharczykL/radarr-healthcheck

The actual script I have now for Radarr v3 (tagged as `preview` in your image) that works just fine is:

```bash
#!/bin/bash
curl ${RADARR_URL}/api/v3/health?apiKey=${APIKEY} 2>&1 | grep -q error
if [ "$?" -eq 1 ]
then
  echo "No errors."
	exit 0
else
  echo "Errors occurred. Check the web interface."
	exit 1
fi
```

If there's interest, I would create a PR.

**Comment by j0nnymoe** [comment]
Hey, sorry we don't have any plans to add healthcheck within our containers, ref: https://github.com/linuxserver/docker-tautulli/issues/79#issuecomment-546721863 .

**Comment by GAS85** [comment]
Simply add to your docker compose for radarr:

```yaml
    healthcheck:
      test: curl -f http://localhost:7878/api/v3/health?apikey=<API KEY> || exit 1
      interval: 5m00s
      timeout: 10s
      retries: 2
      start_period: 30s
```
