### ISSUE TITLE
Radarr v3 Not Propagating Files in Config Folder / Unreachable (RaspberryPi4)

### ISSUE THREAD

**Issue by gist901** [linuxserver/docker-radarr#118]
Hi all,

I am really excited to try the radarr v3 on my raspberry pi 4 ( 2gb ). I have been using the latest version of Radarr in docker up to this point, v0.2.0.1504. 

I created a new YAML file and pointed the config folder to a new folder, not to my existing V2 folder. This was done in case there was an issue or need to roll back the settings.

The script successfully creates a new config folder, but no files propagate in the folder and Radarr v3 is unreachable.

YAML config:
```
version: '2.1'

services:
  radarr:
    container_name: radarr
    image: ghcr.io/linuxserver/radarr
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=America/New_York
      - UMASK_SET=022
    ports:
      - 7878:7878
    volumes:
      - /mnt/dockerConfig/radarr-v3:/config
      - /mnt/movies:/movies
      - /mnt/downloads:/downloads
    restart: unless-stopped
```

My docker version is:
```
Client:
 Debug Mode: false

Server:
 Containers: 5
  Running: 5
  Paused: 0
  Stopped: 0
 Images: 11
 Server Version: 19.03.13
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 8fba4e9a7d01810a393d5d25a3621dc101981175
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.4.79-v7l+
 Operating System: Raspbian GNU/Linux 10 (buster)
 OSType: linux
 Architecture: armv7l
 CPUs: 4
 Total Memory: 1.872GiB
 Name: raspberrypi2gb
 ID: U5CF:AL5Z:QUGR:IAFS:TGSY:SFTD:UX2G:Z6B2:OUN4:3Z6F:X25V:23SH
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

Docker logs from radarr:

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing...
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 10-adduser: executing...

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support the app dev(s) visit:
Radarr: https://opencollective.com/radarr

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1001
User gid:    1001
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing...
[cont-init.d] 30-config: exited 0.
[cont-init.d] 99-custom-scripts: executing...
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
```
Docker image being used:

```

            "Labels": {
                "build_version": "Linuxserver.io version:- 3.0.0.4204-ls85 Build-date:- 2020-11-29T01:23:40-05:00",
                "maintainer": "thelamer"
            }
        },
        "Architecture": "arm",
        "Os": "linux",
```
