### ISSUE TITLE
Permissions issue in latest branch

### ISSUE THREAD

**Issue by RWatson0412** [linuxserver/docker-radarr#127]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

When trying to import by movies library, I would consistently receive the following error:
```
2020-12-29 15:21:50.2|Trace|DiskProviderBase|Directory '/movies/' isn't writable. Access to the path '/movies/radarr_write_test.txt' is denied.
2020-12-29 15:21:51.0|Trace|RadarrErrorPipeline|Handling Exception
2020-12-29 15:21:51.0|Warn|RadarrErrorPipeline|Invalid request Validation failed:
 -- Path: Folder is not writable by user abc
```
This was despite the fact that I had thoroughly checked file permissions up to and including manually logging in with the abc and creating the file in the /movies directory myself. 

I was able to resolve this issue for myself by switching from the latest to the nightly tag which worked immediately with no other changes made between tests.

------------------------------

## Expected Behavior

Media imports when directory is selected.

## Current Behavior

Unexpected and unexplained file permissions errors.

## Steps to Reproduce

1. Create container using latest tag.
2. Connect via web client.
3. Import movies.
4. Error occurs.

## Environment
**OS:** Docker on Arch
**CPU architecture:** x86_64
**How docker service was installed:** ghcr.io/linuxserver/radarr:latest pulled with docker-compose.

## Command used to create docker container (run/create/compose/screenshot)
**Relevant Docker-Compose Section:** 
```
   radarr:
      image: ghcr.io/linuxserver/radarr:nightly
      container_name: radarr
      security_opt:
         - no-new-privileges:true
      networks:
         - network
      environment:
         - PUID=1000
         - PGID=1000
         - TZ=$TZ
         - UMASK_SET=022
      volumes:
         - /mnt/share/Downloads:/downloads
         - /mnt/share/Movies:/movies
         - /home/username/docker/radarr:/config
      ports:
         - 7878:7878
      restart: unless-stopped
```
