### ISSUE TITLE
Failed to create CoreCLR

### ISSUE THREAD

**Issue by josh-sachs** [linuxserver/docker-radarr#137]
Updated this morning to latest image, which now fails to start with

```
today at 11:58 AM  -------------------------------------
today at 11:58 AM            _         ()
today at 11:58 AM           | |  ___   _    __
today at 11:58 AM           | | / __| | |  /  \
today at 11:58 AM           | | \__ \ | | | () |
today at 11:58 AM           |_| |___/ |_|  \__/
today at 11:58 AM  
today at 11:58 AM  
today at 11:58 AM  Brought to you by linuxserver.io
today at 11:58 AM  -------------------------------------
today at 11:58 AM  
today at 11:58 AM  To support the app dev(s) visit:
today at 11:58 AM  Radarr: https://opencollective.com/radarr
today at 11:58 AM  
today at 11:58 AM  To support LSIO projects visit:
today at 11:58 AM  https://www.linuxserver.io/donate/
today at 11:58 AM  -------------------------------------
today at 11:58 AM  GID/UID
today at 11:58 AM  -------------------------------------
today at 11:58 AM  
today at 11:58 AM  User uid:    1000
today at 11:58 AM  User gid:    999
today at 11:58 AM  -------------------------------------
today at 11:58 AM  
today at 11:58 AM  [cont-init.d] 10-adduser: exited 0.
today at 11:58 AM  [cont-init.d] 30-config: executing... 
today at 11:58 AM  [cont-init.d] 30-config: exited 0.
today at 11:58 AM  [cont-init.d] 99-custom-scripts: executing... 
today at 11:58 AM  [custom-init] no custom files found exiting...
today at 11:58 AM  [cont-init.d] 99-custom-scripts: exited 0.
today at 11:58 AM  [cont-init.d] done.
today at 11:58 AM  [services.d] starting services
today at 11:58 AM  [services.d] done.
today at 11:58 AM  Failed to create CoreCLR, HRESULT: 0x80004005
today at 11:59 AM  Failed to create CoreCLR, HRESULT: 0x80004005
today at 11:59 AM  Failed to create CoreCLR, HRESULT: 0x80004005
today at 11:59 AM  Failed to create CoreCLR, HRESULT: 0x80004005
today at 11:59 AM  Failed to create CoreCLR, HRESULT: 0x80004005
today at 11:59 AM  Failed to create CoreCLR, HRESULT: 0x80004005
today at 11:59 AM  Failed to create CoreCLR, HRESULT: 0x80004005
today at 11:59 AM  Failed to create CoreCLR, HRESULT: 0x80004005
today at 11:59 AM  Failed to create CoreCLR, HRESULT: 0x80004005
```

Following are relevant compose args: 

```
image: linuxserver/radarr:latest
    container_name: radarr
    restart: always
    networks:
      - t2_proxy
    security_opt:
      - no-new-privileges:true
    ports:
      - "7878:7878"

    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - ${DROBO}/services/vhdx/radarr:/config
      - ${TMP}/radarr:/tmp
      - ${DROBO}:/data
      - ${DROBO}:/drobo
    
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
```

FWIW I also update `linuxserver/sonarr:latest` this morning which has no issues.  I assume they are pretty similar in terms of environment.
