### ISSUE TITLE
Nightly not getting updated since version 4.0.0.5146

### ISSUE THREAD

**Issue by foux** [linuxserver/docker-radarr#146]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

Using the `nightly` tag of the image, the radarr version isn't being updated. The last one available on LinuxServer is 4.0.0.5146 while the latest upstream one is (at the time of this writing) 4.0.0.5165
------------------------------

## Expected Behavior
Get a new image of LinuxServer container when an upstream nightly version is available

## Current Behavior
No new LinuxServer image since 4.0.0.5146

## Steps to Reproduce
1. A new version is provided upstream
2. Try to pull the new LinuxServer image
3. No new image available

## Environment
**OS:** Linux
**CPU architecture:** x86_64
**How docker service was installed:** : Arch official repo

## Command used to create docker container (run/create/compose/screenshot)
```
version: "3"

services:
  radarr:
    image: ghcr.io/linuxserver/radarr:nightly
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=200
      - TZ=Europe/Paris
    volumes:
      - ../../datas/radarr:/config
      - /merged/medias:/merged/medias
    labels:
      - traefik.http.routers.radarr.entrypoints=web
      - traefik.http.routers.radarr.rule=Host(`xxxxx`)
      - traefik.http.routers.radarr.middlewares=https-redirect
      - traefik.http.routers.radarr-tls.entrypoints=websecure
      - traefik.http.routers.radarr-tls.rule=Host(`xxxxx`)
      - traefik.http.routers.radarr-tls.tls=true
      - traefik.http.routers.radarr-tls.tls.certresolver=letsencrypt-tls
    restart: unless-stopped
    networks:
      - web
```
