### ISSUE TITLE
After update Radarr doesn't want to start and seems to want to recreate database (and fails)

### ISSUE THREAD

**Issue by djmulder** [linuxserver/docker-radarr#170]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
Started up with old database

## Current Behavior
Tries to start up with a new database (logs show it trying to create tables like config and 

## Steps to Reproduce
1. All I did was update to radarr:latest 

## Environment
**OS:** Unraid 6.9.2
**CPU architecture:** x86_64
**How docker service was installed:**
Using docker-compose bundled with VPN network

## Command used to create docker container (run/create/compose/screenshot)
    radarr:
        container_name: radarr
        image: linuxserver/radarr:latest
        cpuset: "7,8,9,23,24,25"
        ports:
            - "7878:7878"
        depends_on:
            - transmission
            - nzbget
            - jackett
        volumes:
            - radarr:/config
            - downloaders:/downloads
            - movies:/movies
        environment:
            PUID: 99
            PGID: 100
            TZ: "Europe/Amsterdam"
    radarr: 
      driver: local
      driver_opts: 
        type: none
        device: /mnt/cache/appdata/radarr
        o: bind
    downloaders:
      driver: local
      driver_opts: 
        type: none
        device: /mnt/user0/downloaders
        o: bind
    movies: 
      driver: local
      driver_opts: 
        type: none
        device: /mnt/user0/public/Movies
        o: bind

## Docker logs
https://pastebin.com/8etFy4bs

**Comment by KimTEriksson** [comment]
I have the same issue on ubuntu first run

**Comment by benjamin4453** [comment]
I have the same issue, here are the info:

OS: Ubuntu 22.04
CPU architecture: x86_64
Service is installed via docker compose:
```
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - /home/benjamin/config:/config
      - /home/benjamin/movies:/movies
      - /home/benjamin/downloads:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped
```
Logs are attached to this comment.
[2022-11-12-radarr.txt](https://github.com/linuxserver/docker-radarr/files/9995550/2022-11-12-radarr.txt)
