### ISSUE TITLE
4.1.0.6175 unable to communicate with other apps (cannot resolve local names?)

### ISSUE THREAD

**Issue by ShanDestromp** [linuxserver/docker-radarr#175]
Had an instance running/updating for months, talking with associated local (same machine / docker instance) images fine.  Updated to latest image and now Radarr can't communicate with images as expected.  It *can* communicate externally (eg searching a new movie works as expected, I see posters and synopsis ) but fails with internal hostname-based addresses.  If I change to the docker/portainer(?) provided IP of the stack (ex 172.19.0.1) it works again.  To be clear **nothing** has changed with my network / portainer / docker otherwise, the Radarr image was the only thing updated; and Sonarr (for ex) is currently still working with same type of setup fine.

------------------------------

## Expected Behavior
Radarr to talk to Prowlarr, NZBGet etc via hostname as it has for months.

## Current Behavior
"Name does not resolve" errors

## Steps to Reproduce

1. Update previously working instance to 4.1.0.6175
2. Radarr now doesn't work

## Environment
**OS:** dock@spacedock:~$ uname -a
Linux spacedock 4.19.0-19-amd64 #1 SMP Debian 4.19.232-1 (2022-03-07) x86_64 GNU/Linux

**CPU architecture:** x86_64
**How docker service was installed:**

## Command used to create docker container (run/create/compose/screenshot)
Run via portainer, updated with Watchtower overnight

## Docker logs
https://pastebin.com/ZDhpwVVM

**Comment by SourCheeks** [comment]
I have the same issue, rolling back to 4.0.5.5981 fixes it for me

**Comment by ShanDestromp** [comment]
@SourCheeks I manually shell'd into the container with `docker exec -it ContainerName /bin/bash` and edited my `/etc/hosts` file (just `echo IP Hostname >> /etc/hosts` adds to the end of the file) to include a manual routing to the pertinent hostname.  I had to add the universal troubleshooting mods to the container in order to have access to ping and the like for testing purposes but isn't otherwise necessary (add `DOCKER_MODS: linuxserver/mods:universal-tshoot` to the environment section of the radarr portion of your stack config if you want it).

This gets me a working latest version, the downside is this change gets nuked anytime the container restarts.  I'm sure I could script something up to redo it on container restart but that's straying further from source than I'd like.  Hopefully a proper fix happens sooner rather than later.

**Comment by j0nnymoe** [comment]
@gil `+1` is not helpful. Please provide information like the OP. 

@ShanDestromp Please provide the compose info you used to deploy the container or if you have used portainer's gui for deploying, some screenshots would be nice. 

We've had no other reports of this issue so maybe portainer and/or watchtower are doing something.

Fwiw - we do not recommend using portainer for deployment of our containers nor do we recommend using watchtower for updating.

**Comment by vilgotf** [comment]
I hit this with podman 4.1.0 (rootless). No real interesting config (just `-v` `PUID` etc.).
Worked around by hardcoding IP addresses instead of my hostname for indexers and download clients

**Comment by j0nnymoe** [comment]
@vilgotf I appreciate you think there is no real interesting config, but any information you can give us makes it 100x more easier to help try and diagnose these issues. We don't ask for this information for no reason.

**Comment by gil** [comment]
@j0nnymoe I'm sorry, some more info:

## Expected Behavior

Radarr to talk to Deluge and Jackett.

## Current Behavior

"Name does not resolve" errors

## Steps to Reproduce

- Update previously working instance to 4.1.0.6175
- Radarr now doesn't work

## Environment:

- gil@NAS:~$ uname -a
  - Linux NAS 4.4.59+ #25556 SMP PREEMPT Thu Mar 4 18:03:46 CST 2021 x86_64 GNU/Linux synology_apollolake_218+
- CPU architecture:
  - x86_64

## How docker service was installed:

Synology DSM official Docker package.

## Command used to create docker container (run/create/compose/screenshot)

`docker-compose.yml`:

```
  radarr:
    image: lscr.io/linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1030
      - PGID=100
      - TZ=Europe/Amsterdam
    volumes:
      - /volume1/homes/gil/docker-data/radarr/config:/config
      - /volume1/downloads:/downloads
    ports:
      - "7878:7878"
    restart: unless-stopped
  jackett:
    image: lscr.io/linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1030
      - PGID=100
      - TZ=Europe/Amsterdam
      - AUTO_UPDATE=true
    volumes:
      - /volume1/homes/gil/docker-data/jackett/config:/config
      - /volume1/homes/gil/docker-data/jackett/downloads:/downloads
    ports:
      - "9117:9117"
    restart: unless-stopped
```

Deluge is not running on Docker. I always used my NAS' hostname for them to communicate, so there's no network configured on Docker for that.

## Docker logs

Will update here after I upgrade to `4.1.0.6175` again. I reverted to the tag `version-4.0.5.5981` for now.

**Comment by ShanDestromp** [comment]
@j0nnymoe below is my full compose file.

> gil +1 is not helpful. Please provide information like the OP.

> We've had no other reports of this issue

You've got two others in this bug report alone; that until today was ignored.

> so maybe portainer and/or watchtower are doing something.

Watchtower simply checks for new builds and pulls and restarts containers on a schedule.  It doesn't interact with them otherwise, and if there isn't an updated docker build it ignores them.

> Fwiw - we do not recommend using portainer for deployment of our containers nor do we recommend using watchtower for updating.

Maybe you have time to hand-manage and update 25+ containers but I don't; so I'll use the tools available to me.

**TO BE EXPLICITLY CLEAR** the only thing that changed in my setup was updating radarr to *.6175.  I had not modified my compose file, made any changes to the base system nor my network setup.  Sonarr, Prowlarr etc are all operating normally, only Radarr is having issues.

```
services:
# Transmission client
  transmission:
    container_name: transmission
    environment:
      PGID: '1001'
      PUID: '1000'
      TZ: America/New_York
    image: ghcr.io/linuxserver/transmission
    logging:
      options:
        max-size: 10m
    ports:
    - published: 9091
      target: 9091
    - published: 51413
      target: 51413
    - protocol: udp
      published: 51413
      target: 51413
    restart: unless-stopped
    volumes:
    - /home/dock/config/transmission:/config:rw
    - Incoming:/downloads:rw

# Usenet downloader
  nzbget:
    container_name: nzbget
    environment:
      PGID: '1001'
      PUID: '1000'
      TZ: America/New_York
    image: ghcr.io/linuxserver/nzbget
    logging:
      options:
        max-size: 10m
    ports:
    - published: 6789
      target: 6789
    restart: unless-stopped
    volumes:
    - /home/dock/config/nzbget:/config:rw
    - Incoming:/downloads:rw

# Prowlarr indexer aggregator
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    environment:
      TZ: America/New_York
      PGID: '1001'
      PUID: '1000'
    volumes:
      - /home/dock/config/prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped

# Movie management
  radarr:
    container_name: radarr
    environment:
      PGID: '1001'
      PUID: '1000'
      TZ: America/New_York
      UMASK: '002'
    image: ghcr.io/linuxserver/radarr
    logging:
      options:
        max-size: 10m
    ports:
    - published: 7878
      target: 7878
    restart: unless-stopped
    volumes:
    - /home/dock/config/radarr:/config:rw
    - Incoming:/downloads:rw
    - Movies:/movies:rw
  
# TV management
  sonarr:
    container_name: sonarr
    environment:
      PGID: '1001'
      PUID: '1000'
      TZ: America/New_York
      UMASK: '002'
    image: ghcr.io/linuxserver/sonarr
    logging:
      options:
        max-size: 10m
    ports:
    - published: 8989
      target: 8989
    restart: unless-stopped
    volumes:
    - TV:/TV:rw
    - /home/dock/config/sonarr:/config:rw
    - Incoming:/downloads:rw
    - 
# Bazarr subtitle downloader / manager
  bazarr:
    image: lscr.io/linuxserver/bazarr
    container_name: bazarr
    environment:
      PUID: 1000
      PGID: 1000
      TZ: America/New_York
    volumes:
      - /home/dock/config/bazarr:/config
      - Movies:/movies:rw
      - TV:/TV:rw
      - Incoming:/downloads:rw
    ports:
      - 6767:6767
    restart: unless-stopped

volumes:
# Radarr
  Movies:
    driver: local
    driver_opts:
      device: :/mnt/tardis/Media/Movies
      o: addr=192.168.1.2
      type: nfs

# Sonarr
  TV:
    driver: local
    driver_opts:
      device: :/mnt/tardis/Media/TV
      o: addr=192.168.1.2
      type: nfs

# Shared source directory for *rr
  Incoming:
    driver: local
    driver_opts:
      device: :/mnt/tardis/dalek/incoming
      o: addr=192.168.1.2
      type: nfs
```
