### ISSUE TITLE
[BUG] Can't start Radarr

### ISSUE THREAD

**Issue by vmvelev** [linuxserver/docker-radarr#210]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When starting Radarr with Docker Compose, the URL can't be reached.

### Expected Behavior

Radarr should work as expected.

### Steps To Reproduce

1. On Ubuntu 20.04.6 LTS
2. With Docker version 24.0.2, build cb74dfc
3. And docker-compose.yaml:
```
---
version: "2.1"
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /home/vmvelev/configs:/config
      - /home/vmvelev/media/shows:/data/tvshows
      - /home/vmvelev/media/movies:/data/movies
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    restart: unless-stopped
  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /home/vmvelev/configs:/config
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /home/vmvelev/configs:/config
      - /home/vmvelev/media/shows:/tv #optional
      - /home/vmvelev/media/downloads:/downloads #optional
    ports:
      - 8989:8989
    restart: unless-stopped
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /home/vmvelev/configs:/config
      - /home/vmvelev/media/movies:/movies #optional
      - /home/vmvelev/media/downloads:/downloads #optional
    ports:
      - 7878:7878
    restart: unless-stopped
  nzbget:
    image: lscr.io/linuxserver/nzbget:latest
    container_name: nzbget
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - NZBGET_USER=vmvelev #optional
      - NZBGET_PASS=****** #optional
    volumes:
      - /home/vmvelev/configs:/config
      - /home/vmvelev/media/downloads:/downloads #optional
    ports:
      - 6789:6789
    restart: unless-stopped
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /home/vmvelev/configs:/config
      - /home/vmvelev/media/movies:/movies #optional
      - /home/vmvelev/media/shows:/tv #optional
    ports:
      - 6767:6767
    restart: unless-stopped
  sqlitebrowser:
    image: lscr.io/linuxserver/sqlitebrowser:latest
    container_name: sqlitebrowser
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /home/vmvelev/configs:/config
    ports:
      - 3000:3000
      - 3001:3001
    restart: unless-stopped
```
4. Try to connect to Radarr via web browser - it does not work.

### Environment

```markdown
- OS: Ubuntu 20.04.6 LTS
- How docker service was installed:

curl -fsSL https://get.docker.com -o get-docker.sh && \
sh get-docker.sh
```
```


### CPU architecture

x86-64

### Docker creation

```bash
---
version: "2.1"
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /home/vmvelev/configs:/config
      - /home/vmvelev/media/shows:/data/tvshows
      - /home/vmvelev/media/movies:/data/movies
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    restart: unless-stopped
  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /home/vmvelev/configs:/config
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /home/vmvelev/configs:/config
      - /home/vmvelev/media/shows:/tv #optional
      - /home/vmvelev/media/downloads:/downloads #optional
    ports:
      - 8989:8989
    restart: unless-stopped
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /home/vmvelev/configs:/config
      - /home/vmvelev/media/movies:/movies #optional
      - /home/vmvelev/media/downloads:/downloads #optional
    ports:
      - 7878:7878
    restart: unless-stopped
  nzbget:
    image: lscr.io/linuxserver/nzbget:latest
    container_name: nzbget
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - NZBGET_USER=vmvelev #optional
      - NZBGET_PASS=****** #optional
    volumes:
      - /home/vmvelev/configs:/config
      - /home/vmvelev/media/downloads:/downloads #optional
    ports:
      - 6789:6789
    restart: unless-stopped
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /home/vmvelev/configs:/config
      - /home/vmvelev/media/movies:/movies #optional
      - /home/vmvelev/media/shows:/tv #optional
    ports:
      - 6767:6767
    restart: unless-stopped
  sqlitebrowser:
    image: lscr.io/linuxserver/sqlitebrowser:latest
    container_name: sqlitebrowser
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /home/vmvelev/configs:/config
    ports:
      - 3000:3000
      - 3001:3001
    restart: unless-stopped
```
```


### Container logs

```bash
vmvelev@media:~$ sudo docker logs d1cb3261ac36
[migrations] started
[migrations] no migrations found
───────────────────────────────────────

      ██╗     ███████╗██╗ ██████╗
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝

   Brought to you by linuxserver.io
───────────────────────────────────────

To support the app dev(s) visit:
Radarr: https://opencollective.com/radarr

To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    1000
User GID:    1000
───────────────────────────────────────

[custom-init] No custom files found, skipping...
[Info] Bootstrap: Starting Radarr - /app/radarr/bin/Radarr - Version 4.5.2.7388
[Info] AppFolderInfo: Data directory is being overridden to [/config]
[Debug] Bootstrap: Console selected
[Info] AppFolderInfo: Data directory is being overridden to [/config]
[Info] AppFolderInfo: Data directory is being overridden to [/config]
[Info] MigrationController: *** Migrating data source=/config/radarr.db;cache size=-20000;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 ***
[Info] MigrationController: *** Migrating data source=/config/logs.db;cache size=-20000;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 ***
[Info] UpdaterConfigProvider: External updater uses branch master instead of the currently selected main, changing to master.
[Info] CommandExecutor: Starting 2 threads for tasks.
```
```
