### ISSUE TITLE
[BUG] Trying to upgrade from 4.1.0.6175-ls141 to latest

### ISSUE THREAD

**Issue by kurktchiev** [linuxserver/docker-radarr#213]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I switch my docker-compose to pull the latest Radarr image, Radarr never actually starts up. The whole log file can be seen below:

```
[migrations] started
[migrations] no migrations found
───────────────────────────────────────
      ██╗     ███████╗██╗ ██████╗ 
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝ 
   Brought to you by linuxserver.io
───────────────────────────────────────
To support the app dev(s) visit:
Radarr: https://opencollective.com/radarr
To support LSIO projects visit:
https://www.linuxserver.io/donate/
───────────────────────────────────────
GID/UID
───────────────────────────────────────
User UID:    1024
User GID:    100
───────────────────────────────────────
[custom-init] No custom files found, skipping...
```

No matter what I do it just sits on the custom-init and never gets past it.

### Expected Behavior

Fire up and finish starting up

### Steps To Reproduce

1. Start with this compose:
```
---
version: "2.1"
services:
  radarr:
    image: lscr.io/linuxserver/radarr:4.1.0.6175-ls141
    container_name: radarr
    # network_mode: host
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    environment:
      - PUID=1024
      - PGID=100
      - TZ=America/New_York
    volumes:
      - /volume1/docker/radarr:/config
      - /volume1/New Stuff:/downloads
      - /volume1/New Stuff:/volume1/New Stuff
      - /volume1/Movies:/movies
    ports:
      - 17878:7878
    restart: unless-stopped
```

See that things start up as expected. 

Switch to this compose:
```
---
version: "2.1"
services:
  radarr:
    # image: lscr.io/linuxserver/radarr:4.1.0.6175-ls141
    image: lscr.io/linuxserver/radarr
    container_name: radarr
    # network_mode: host
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    environment:
      - PUID=1024
      - PGID=100
      - TZ=America/New_York
    volumes:
      - /volume1/docker/radarr:/config
      - /volume1/New Stuff:/downloads
      - /volume1/New Stuff:/volume1/New Stuff
      - /volume1/Movies:/movies
    ports:
      - 17878:7878
    restart: unless-stopped
```
Watch it get stuck on the line above and never move past it.

### Environment

```markdown
- OS: Synology 6.x
- How docker service was installed: docker-compose
```

### CPU architecture

x86-64

### Docker creation

```bash
---
version: "2.1"
services:
  radarr:
    # image: lscr.io/linuxserver/radarr:4.1.0.6175-ls141
    image: lscr.io/linuxserver/radarr
    container_name: radarr
    # network_mode: host
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    environment:
      - PUID=1024
      - PGID=100
      - TZ=America/New_York
    volumes:
      - /volume1/docker/radarr:/config
      - /volume1/New Stuff:/downloads
      - /volume1/New Stuff:/volume1/New Stuff
      - /volume1/Movies:/movies
    ports:
      - 17878:7878
    restart: unless-stopped
```

### Container logs

```bash
[migrations] started
[migrations] no migrations found
───────────────────────────────────────
      ██╗     ███████╗██╗ ██████╗ 
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝ 
   Brought to you by linuxserver.io
───────────────────────────────────────
To support the app dev(s) visit:
Radarr: https://opencollective.com/radarr
To support LSIO projects visit:
https://www.linuxserver.io/donate/
───────────────────────────────────────
GID/UID
───────────────────────────────────────
User UID:    1024
User GID:    100
───────────────────────────────────────
[custom-init] No custom files found, skipping...
```
