### ISSUE TITLE
After about 10 hours, radarr throws the warning "Root folder '/movies/' was not found"

### ISSUE THREAD

**Issue by rbhalla** [linuxserver/docker-radarr#25]
Running on Ubuntu 16.04.
I'm using docker compose to configure this container. The config is below:

```
version: '3.4'
services:
  radarr:
    container_name: radarr
    ports:
      - 7878:7878
    image: linuxserver/radarr
    restart: always
    network_mode: host
    environment:
      - PGID=0
      - PUID=0
      - TZ=Europe/London
    volumes:
      - type: volume
        source: radarr-config
        target: /config
      - /var/lib/deluge/completed:/downloads
      - /mnt/media/movies:/movies

volumes:
  radarr-config:
    name: radarr-config
```

I have a single volume (again, managed by docker compose). The other two locations exist outside of docker. The `/mnt/media` is a fuse mount managed by rclone. 

Oddly, a `docker-compose down` with a `docker-compose up` fixes it for about another 10 hours. I am also using the sonarr image maintained by linuxserver and it has the exact same issue. 

When I `docker exec` into the container, I can't see anything in the `/movies` folder, but when I `cd` into the mount directory directly, I can still see everything.

Any thoughts on why this might be occurring?
