### ISSUE TITLE
Resolved: Very High CPU Usage from Mono PID after latest Radarr container update

### ISSUE THREAD

**Issue by pl77** [linuxserver/docker-radarr#39]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
	

After the latest update my radarr service started running at maximum CPU utilization continuously.  Running top/htop it was apparent that the "mono" PID was the cause of this issue.  After investigating all mono-based containers I narrowed it down to Radarr.  Radarr was recently pulled and updated (within last week) and the error began after that.  

Ubuntu 18.04LTS, 6 core i7 with 64GB RAM, radarr installed on SSD. 

used docker-compose: 

```
version: '3.7'
services:
  radarr:
    container_name: radarr
    image: linuxserver/radarr:latest
    restart: unless-stopped
    stop_grace_period: 2m
    volumes:
      - radarrconfig:/config
      - movies:/movies
      - kidsmovies:/KidsMovies
      - sab_downloads:/downloads
      - tb1_qb:/qb
    environment:
      PGID: 1000
      PUID: 1000
      TZ: America/Toronto
      MONO_TLS_PROVIDER: legacy
    expose:
      - "7878"
    networks:
      - webproxy
```

No relevant log messages related to a runaway Mono process.  Last log entry was hours prior to any issue emerging.

No symlinks used...

After some troubleshooting (it took a bit to figure out it was even Radarr causing the problem, as the CPU was being used by the mono PID) I determined that **the "MONO_TLS_PROVIDER: legacy" option was the root of the cpu problems**.  Upon removing that environmental variable and rebooting the radarr container the problem disappeared.

Just providing some feedback in case others (like myself) end up hear searching for MONO RADARR HIGH CPU USAGE DOCKER LINUX or something similar. it's a quick fix, but not immediately apparent.

This should not affect default users, as there is no instruction to enable that environmental variable.  This only affect users who were being impacted by previous errors on earlier builds, such as the following issue:

https://github.com/linuxserver/docker-radarr/issues/17

##  Thanks, team linuxserver.io

And thank you, team linuxserver.io, for the amazing work you all do in giving us these turn-key images.  Much appreciated.

**Comment by aptalca** [comment]
Thanks for troubleshooting and confirming that adding the env var was the issue.

Since we don't recommend adding that var in our docs, I'll go ahead and close this issue but we'll keep it in mind if any other user experiences similar issues.

**Comment by pl77** [comment]
Yes, thanks @aptalca, I meant to suggest imediately closing this in my original post.

I just wanted to make sure it was recorded somewhere so google would pick it up and save someone else a bunch of time tracking it down!

**Comment by danmandle** [comment]
I am also experiencing this issue with or without the `MONO_TLS_PROVIDER` flag set. `docker stats` shows that radarr is running 75%+ CPU utilization when idling. I'm running linuxserver/radarr:latest Image ID 3c60aa8e867a, Radarr Ver. 0.2.0.1358 develop. I also have sonarr running and the CPU usage for that container is normal. 

```
  radarr:
    container_name: radarr
    image: linuxserver/radarr
    volumes:
      - /var/docker/radarr:/config
      - /mnt/diskstation/videos/Movies/:/movies
      - /mnt/diskstation/videos/rutorrent:/downloads
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=America/Denver
    ports:
      - 7878
    labels:
      - "traefik.frontend.rule=Host:radarr.docker.df"
    dns: 10.5.0.1
```
`config.xml`
```
<Config>
  <LogLevel>Info</LogLevel>
  <Port>7878</Port>
  <UrlBase></UrlBase>
  <BindAddress>*</BindAddress>
  <SslPort>9898</SslPort>
  <EnableSsl>False</EnableSsl>
  <ApiKey>XXXXXXXXXXXXXXX</ApiKey>
  <AuthenticationMethod>None</AuthenticationMethod>
  <Branch>develop</Branch>
  <LaunchBrowser>True</LaunchBrowser>
  <SslCertHash></SslCertHash>
  <UpdateMechanism>BuiltIn</UpdateMechanism>
</Config>
```

Relevant system info
```
danmandle@docker:~$ sudo lshw -short
H/W path           Device           Class      Description
==========================================================
                                    system     VMware Virtual Platform
/0                                  bus        440BX Desktop Reference Platform
/0/0                                memory     86KiB BIOS
/0/4                                processor  Intel(R) Xeon(R) CPU E5-2620 0 @ 2.00GHz
/0/4/15                             memory     16KiB L1 cache
/0/25                               memory     18GiB System Memory
/0/25/0                             memory     16GiB DIMM DRAM EDO
/0/25/1                             memory     2GiB DIMM DRAM EDO
/0/100/10          scsi32           storage    53c1030 PCI-X Fusion-MPT Dual Ultra320 SCSI
/0/100/10/0.0.0    /dev/sda         disk       128GB Virtual disk
/0/100/10/0.0.0/1  /dev/sda1        volume     1023KiB BIOS Boot partition
/0/100/10/0.0.0/2  /dev/sda2        volume     119GiB EXT4 volume
/0/100/10/0.1.0    /dev/sdb         volume     4TiB Virtual disk
/0/1/0.0.0/0/2                      volume     15EiB Windows FAT volume
```

**Comment by aptalca** [comment]
Mine's idling at 0.01%-0.13% with occasional spikes to ~45%, whenever it does some processing.

Did you check radarr logs?

Did you modify the config.xml manually?

**Comment by pl77** [comment]
In the [related Radarr thread](https://github.com/Radarr/Radarr/issues/3278) they have a couple of suggestions/suspicions you could narrow down:

1. Does this occur after you kill the container and restart the process?
2. Does this occur after a fresh reboot of the server?  Sometimes docker doesn't kill the underlying mono process PIDs and they just keep mucking away chewing up CPU cycles.  Stop any mono containers (Sonarr/Radarr/Lidarr/etc) and then kill any stray mono processes before restarting them and see if that fixes it. 
3. One thing I did was set a `stop_grace_period: 2m` to all my docker containers.  Most don't need nearly that amount of time but it's drastically cut down on the number of file/disk/database errors that I've encountered when I was using the default 10 second 'shut down or die' docker parameter. I have not seen this issue emerge again since I wrote up this issue and made sure the Legacy flag wasn't set.

The only other change I've made to my configuration that isn't really default is relaxing the ulimits so radar has a bit more breathing room.  I can't remember what the original default values are, but I pass these through my docker-compose file:

```yaml
version: '3.7'
services:
  radarr:
    container_name: radarr
    image: linuxserver/radarr:latest
    restart: unless-stopped
    stop_grace_period: 2m
    ulimits:
      nproc: 500000
      nofile:
        soft: 500000
        hard: 900000
```

They're probably excessively large, but I have a pretty powerful server and I didn't want my apps twiddling their thumbs waiting for a file handle to become available.  Especially important on apps that churn through a pile of tiny XML files.
