### ISSUE TITLE
Unable to add Deluge or Rutorrent download client

### ISSUE THREAD

**Issue by leveled** [linuxserver/docker-radarr#54]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
	

Host OS: Ubuntu 18.0.4 LTS

I've tried this both with the Deluge service living in it's own network and, living in the same network as Radarr, it does not appear to make a difference. I've started a shell on the radarr container and confirmed that the Deluge service is connectable via both hostname and IP address. 

Docker compose file:
```
version: '2' 

services:
    radarr:
        container_name: radarr
        image: linuxserver/radarr
        restart: always
        environment:
          - PUID=1000
          - PGID=1000
          - TZ=Europe/London
        volumes:
          - ${PWD}/config:/config
          - ${PWD}/downloads:/downloads
          - ${PWD}/movies:/movies
        networks:
          - webproxy
          - radarr
        depends_on:
          - deluge
        labels:
          - "traefik.enable=true"
          - "traefik.frontend.rule=Host:radar.xxx.xxx"
          - "traefik.port=7878"
          - "traefik.docker.network=webproxy"
          - "traefik.frontend.auth.basic=xxx"
    deluge:                      
        container_name: deluge-radarr
        image: linuxserver/deluge
        restart: always
        environment:
          - PUID=1000            
          - PGID=1000                                     
          - TZ=Europe/London   
        volumes:                             
          - ${PWD}/deluge-config:/config
          - ${PWD}/deluge-downloads:/downloads
        networks:
          - webproxy  
          - radarr
        labels:             
          - "traefik.enable=true"
          - "traefik.frontend.rule=Host:deluge.xxx.xxx"
          - "traefik.port=8112"
          - "traefik.docker.network=webproxy"

networks:
    webproxy:
        external: true
    radarr:
        external: false
```

Docker logs:
```
radarr    | [Warn] NzbDroneErrorPipeline: Invalid request Validation failed:
radarr    |  -- Authentication failed
radarr    | [Error] Deluge: Unknown method
radarr    |
radarr    | [v0.2.0.1344] NzbDrone.Core.Download.Clients.DownloadClientAuthenticationException: Unknown method
radarr    |   at NzbDrone.Core.Download.Clients.Deluge.DelugeProxy.ProcessRequest[TResult] (NzbDrone.Core.Download.Clients.Deluge.DelugeSettings settings, System.String method, System.Object[] arguments) [0x00066] in C:\projects\radarr-usby1\src\NzbDrone.Core\Download\Clients\Deluge\DelugeProxy.cs:207
radarr    |   at NzbDrone.Core.Download.Clients.Deluge.DelugeProxy.GetVersion (NzbDrone.Core.Download.Clients.Deluge.DelugeSettings settings) [0x00000] in C:\projects\radarr-usby1\src\NzbDrone.Core\Download\Clients\Deluge\DelugeProxy.cs:51
radarr    |   at NzbDrone.Core.Download.Clients.Deluge.Deluge.TestConnection () [0x00000] in C:\projects\radarr-usby1\src\NzbDrone.Core\Download\Clients\Deluge\Deluge.cs:188
radarr    |
radarr    | [Warn] NzbDroneErrorPipeline: Invalid request Validation failed:
radarr    |  -- Authentication failed
```

I'm not using any symlinks
