### ISSUE TITLE
Unable to start radarr

### ISSUE THREAD

**Issue by pike00** [linuxserver/docker-radarr#99]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

## Environment
**OS:** Debain 10 buster      
**CPU architecture:** x86_64
**How docker service was installed:** Using the [convenience script (docker)](https://docs.docker.com/engine/install/debian/#install-using-the-convenience-script) and [following the instructions on this page (docker-compose)](https://docs.docker.com/compose/install/#install-compose)

I recently created a docker-compose.yaml with the following code: 
```
--- version: "2.1"
services:
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1001
      - TZ=America/New_York
      - UMASK_SET=022 #optional
    volumes:
      - /config:/config
      - /home/will/media/movies/:/movies
      - /home/will/media/downloads:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped
```

However, when I run `docker-compose up -d`, the server isn't running. 

Upon inspection of the logs, I believe there is an SQLite error:

```
MigrationLogger: SQL logic error
no such table: MovieFiles
While Processing:
"ALTER TABLE "MovieFiles" ADD COLUMN "Edition" TEXT"

[v0.2.0.1504] System.Exception: SQL logic error
no such table: MovieFiles
```

Here is the full output when I run `docker logs radarr`: [radarr.log](https://github.com/linuxserver/docker-radarr/files/4880567/radarr.log)

**Comment by pike00** [comment]
I figured out the issue. I was trying to configure both linuxserver/sonarr and linuxserver/radarr to the same directory on the host machine (/config). This caused a conflict between sonarr and radarr (as i had setup sonarr first, it continued to work). To solve the problem, make the config directories a sub-folder explicitly (I had assumed the radarr image would have made the subfolder /config/radarr, but it instead dumps everything into /config/). 

Here's the version that now works:
```
---
version: "3.7"
services:
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1001
      - TZ=America/New_York
      - UMASK_SET=022 #optional
    volumes:
      - /config/sonarr:/config
      - /home/will/media/tv/:/tv
      - /home/will/media/downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped


  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1001
      - TZ=America/New_York
    volumes:
      - /config/radarr:/config
      - /home/will/media/movies:/tv
      - /home/will/media/downloads:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped

```
